---

- name: install dependencies apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ docker_dep_packages }}"

- name: install key
  apt_key:
    keyserver: "{{ docker_apt_key_server }}"
    id: "{{ docker_apt_key_id }}"
    state: present
  register: docker_key_installed

- name: add repo
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    update_cache: no
  when: docker_key_installed|success
  register: docker_repo_installed

- name: update apt cache
  apt:
    update_cache: yes
  when: docker_repo_installed|changed

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ docker_packages }}"
  when: docker_repo_installed|success

- name: add docker user_group
  group:
    name: docker
    state: present

- name: install docker-compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_install_path }}"
    owner: root
    group: root
    mode: 0744
  when: docker_compose_enabled

- name: add newrelic user in docker group
  user:
    name: newrelic
    groups: docker
  notify:
    - restart docker
    - restart newrelic-agent
  when: docker_newrelic_support_enabled

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
