---

- name: restart docker
  service:
    name:  "{{ item }}"
    state: restarted
  with_items:
    - docker

- name: restart newrelic-agent
  service:
    name: newrelic-sysmond
    state: restarted
  when: not docker_test_mode
